version: '3'
services:
  lamp:
    build: .
    ports:
      - "81:22"
      - "80:80"
    volumes:
      - ../:/var/www/html
      - ./mariadb:/var/lib/mysql
      - ./php:/etc/php8.1/apache2
    environment:
      MYSQL_ROOT_PASSWORD: password
