version: '3'
services:
  alx_lamp:
    build: .
    ports:
      - "23:22"
      - "80:80"
    volumes:
      - ../:/var/www/html
      - ./mariadb:/var/lib/mysql
      - ./php:/etc/php/8.1/apache2
    environment:
      MYSQL_ROOT_PASSWORD: password
